name: Terratest

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

jobs:

  Runner:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Set Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIAXCPW6SYCROTVMUHU
        aws-secret-access-key: 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
        aws-region: us-east-1

    - name: Checkin app all configuration
      run: go version && terraform version && aws --version

    # - name: Bash
    #   run: cd test
    
    # - name: Module
    #   run: go mod init module/m && go mod tidy
            
    # - name: Test
    #   run: go test