name: Go

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Bash
      run: cd test
    
    - name: Module
      run: go mod init module/m && go mod tidy
            
    - name: Test
      run: go test -v