name: Terratest

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

jobs:

  Runner:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # - name: Set up Go
    #   uses: actions/setup-go@v2
    #   with:
    #     go-version: 1.16

    # - name: Set Terraform
    #   uses: hashicorp/setup-terraform@v1

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${secrets.AWS_ACCESS_KEY_ID}
        aws-secret-access-key: ${secrets.AWS_SECRET_ACCESS_KEY}
        aws-region: us-east-1

    - name: Check app all configuration
      run: aws --version

    # - name: Bash
    #   run: cd test
    
    # - name: Module
    #   run: go mod init module/m && go mod tidy
            
    # - name: Test
    #   run: go test